#!/usr/bin/env python3
"""Generate requirements/django_137_requirements.yml and rules/requirement_mapping.yml.

Usage:  python tools/generate_requirements.py
Validates the catalogue (ids, categories, severities, automation levels,
uniqueness) and fails loudly on any inconsistency.  Adding a requirement is a
one-line change in tools/reqdata_part*.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from reqcommon import CATEGORIES  # noqa: E402
from reqdata_part1 import REQS1  # noqa: E402
from reqdata_part2 import REQS2  # noqa: E402


def main() -> int:
    reqs = REQS1 + REQS2

    # --- validation -------------------------------------------------------
    ids = [r["id"] for r in reqs]
    assert len(ids) == len(set(ids)), "duplicate requirement ids"
    assert len(ids) == 137, f"expected 137 requirements, found {len(ids)}"
    for i, rid in enumerate(ids, start=1):
        assert rid == f"REQ-{i:03d}", f"ids must be sequential: expected REQ-{i:03d}, got {rid}"
    used_categories = sorted({r["category"] for r in reqs})
    for c in used_categories:
        assert c in CATEGORIES, f"unknown category {c}"

    # --- requirements/django_137_requirements.yml -------------------------
    out = []
    for r in reqs:
        out.append({
            "id": r["id"],
            "name": r["name"],
            "category": r["category"],
            "severity": r["severity"],
            "description": r["description"],
            "verification_method": r["verification"],
            "automation_level": r["automation_level"],
            "scanner_mapping": r["scanner_mapping"],
            "cwe": r["cwe"],
            "owasp": r["owasp"],
            "test_definition": (r["scanner_mapping"]["automated"]
                                or r["scanner_mapping"]["dast"]
                                or r["scanner_mapping"]["configuration"]),
            "remediation": r["remediation"],
        })
    req_path = ROOT / "requirements" / "django_137_requirements.yml"
    req_path.parent.mkdir(exist_ok=True)
    req_path.write_text(
        "# Django security requirement catalogue (137 requirements).\n"
        "# GENERATED by tools/generate_requirements.py -- edit tools/reqdata_part*.py\n"
        "# and re-run the generator instead of editing this file by hand.\n"
        + yaml.safe_dump(out, sort_keys=False, width=100, allow_unicode=True),
        encoding="utf-8",
    )

    # --- rules/requirement_mapping.yml ------------------------------------
    mapping = {}
    for r in reqs:
        sm = r["scanner_mapping"]
        mapping[r["id"]] = {
            "sast": sm["sast"],
            "configuration": sm["configuration"],
            "dependencies": sm["dependencies"],
            "network": sm["network"],
            "dast": sm["dast"],
            "automated": sm["automated"],
            "manual": bool(r["manual_review"]),
        }
    map_path = ROOT / "rules" / "requirement_mapping.yml"
    map_path.write_text(
        "# Requirement -> scanner/check rule mapping.\n"
        "# GENERATED by tools/generate_requirements.py -- edit tools/reqdata_part*.py.\n"
        + yaml.safe_dump(mapping, sort_keys=False, width=100),
        encoding="utf-8",
    )

    print(f"wrote {req_path} ({len(reqs)} requirements)")
    print(f"wrote {map_path}")
    print(f"categories used: {len(used_categories)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
