"""Requirement catalogue part 1: REQ-001 .. REQ-070."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from reqcommon import R  # noqa: E402

REQS1 = [
R("REQ-001","Authentication required for protected resources","Authentication","High",
  desc="Every non-public view, API endpoint and resource must require authentication; anonymous access must be an explicit, justified exception.",
  fix="Apply LoginRequiredMixin / IsAuthenticated defaults, remove accidental anonymous routes and justify each public endpoint.",
  ver=["dast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-306"],owasp="A07:2021",
  dast=["DAST-AUTH-001"],tests=["AUTH-001"]),
R("REQ-002","Server-side authorization enforcement","Authorization","Critical",
  desc="Authorization decisions must be enforced server-side for every request; client-side checks are advisory only.",
  fix="Enforce permission checks in views/serializers/middleware; never rely on UI hiding or frontend logic.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-602","CWE-285"],owasp="A01:2021",
  sast=["AUTHZ-OBJECT-001","AUTHZ-002"],tests=["AUTHZ-V-001"]),
R("REQ-003","Explicit role permissions","Authorization","High",
  desc="Role/permission checks must be explicit and reviewed; implicit trust in group membership or flags is not acceptable.",
  fix="Use Django permissions, DRF permission classes or django-rules with explicit role checks on privileged actions.",
  ver=["sast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-285"],owasp="A01:2021",
  sast=["AUTHZ-002"],tests=["AUTHZ-V-001"],manual=True),
R("REQ-004","No cross-user object access","Authorization","Critical",
  desc="A user must not be able to read or modify objects owned by another user (IDOR/BOLA).",
  fix="Scope querysets to request.user and enforce object-level permissions on every detail endpoint.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  sast=["AUTHZ-OBJECT-001"],dast=["DAST-IDOR-001"],tests=["IDOR-001","AUTHZ-H-001"]),
R("REQ-005","Tenant/organization isolation","Multi-tenant","Critical",
  desc="In multi-tenant applications, data of one tenant must never be reachable from another tenant's context.",
  fix="Enforce tenant scoping in managers/querysets and verify isolation with cross-tenant test accounts.",
  ver=["dast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  dast=["DAST-IDOR-001"],tests=["IDOR-001"],manual=True),
R("REQ-006","Administrative actions require elevated authorization","Authorization","High",
  desc="Administrative endpoints and actions must require admin/elevated roles, not just authentication.",
  fix="Protect admin actions with is_staff/superuser checks or dedicated permission classes.",
  ver=["dast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-269"],owasp="A01:2021",
  dast=["DAST-ADMIN-001"],tests=["AUTHZ-V-001"]),
R("REQ-007","External input validation","Input Validation","High",
  desc="All external input (query strings, bodies, headers, files) must be validated for type, length, format and range before use.",
  fix="Use Django forms/DRF serializers with explicit field constraints; reject input that fails validation.",
  ver=["sast","dast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-20"],owasp="A03:2021",
  sast=["SER-001"],dast=["DAST-XSS-001","DAST-SQLI-001"],manual=True),
R("REQ-008","Safe ORM/parameterized database queries","Database","Critical",
  desc="Database access must use the ORM or parameterized queries; SQL built by string concatenation/formatting is forbidden.",
  fix="Use ORM querysets; where raw SQL is unavoidable, pass parameters via params= placeholders.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-89"],owasp="A03:2021",
  sast=["SQLI-001","SQLI-002","SQLI-003","SQLI-004"],dast=["DAST-SQLI-001"],tests=["SQLI-001"]),
R("REQ-009","CSRF protection where applicable","CSRF","High",
  desc="State-changing requests over session authentication must be protected by Django's CSRF framework.",
  fix="Keep CsrfViewMiddleware enabled; justify and scope every csrf_exempt decorator.",
  ver=["configuration","sast","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-352"],owasp="A01:2021",
  sast=["CSRF-001"],conf=["CFG-CSRFMW"],tests=["CSRF-001"]),
R("REQ-010","Django secure password hashing","Authentication","High",
  desc="Passwords must be hashed with a strong adaptive algorithm (Argon2/bcrypt/PBKDF2 with sane iterations), never MD5/SHA1/unsalted.",
  fix="Configure PASSWORD_HASHERS with Argon2 or PBKDF2 first and remove weak hashers.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-916"],owasp="A02:2021",
  conf=["CFG-PWHASH"]),
R("REQ-011","Password validators/strength policy","Authentication","Medium",
  desc="AUTH_PASSWORD_VALIDATORS must enforce minimum length and complexity and block common passwords.",
  fix="Enable UserAttributeSimilarity, MinimumLength(>=10), CommonPassword and NumericPassword validators.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-521"],owasp="A07:2021",
  conf=["CFG-PWVALID"]),
R("REQ-012","Brute-force protection/rate limiting","Authentication","Medium",
  desc="Authentication endpoints must be protected against credential brute force and stuffing (rate limiting, lockout, MFA).",
  fix="Add django-axes or DRF throttling on login/token endpoints and alert on repeated failures.",
  ver=["configuration","sast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-307"],owasp="A07:2021",
  conf=["CFG-THROTTLE"],sast=["RATE-001"],tests=["RATE-001"],manual=True),
R("REQ-013","Secrets not hardcoded","Secrets","Critical",
  desc="SECRET_KEY, API keys, passwords and tokens must come from the environment or a secret manager, never from source code.",
  fix="Load secrets via os.environ/secret manager; rotate every secret found in code and purge it from history.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-798"],owasp="A05:2021",
  sast=["SECRET-001","SECRET-002","SECRET-004","SECRET-005","SECRET-006","SECRET-007"]),
R("REQ-014","Private keys/tokens not committed","Secrets","Critical",
  desc="Private keys, certificates and long-lived tokens must not exist in the repository or artifacts.",
  fix="Remove key material from the repo and history, rotate it, and add secret scanning to CI.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-321"],owasp="A02:2021",
  sast=["SECRET-003","SECRET-004","SECRET-005"]),
R("REQ-015","DEBUG disabled in production","Configuration","High",
  desc="DEBUG must be False in production; DEBUG=True leaks settings, stack traces and enables debug endpoints.",
  fix="Set DEBUG from an environment variable defaulting to False and fail startup if True in production.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-489"],owasp="A05:2021",
  conf=["CFG-DEBUG"]),
R("REQ-016","Explicit ALLOWED_HOSTS; no wildcard","Configuration","High",
  desc="ALLOWED_HOSTS must be an explicit list of valid hostnames; wildcards or empty values with DEBUG=False are unsafe.",
  fix="Enumerate exact hostnames (and their TLS aliases) in ALLOWED_HOSTS; avoid subdomain wildcards unless justified.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-16"],owasp="A05:2021",
  conf=["CFG-ALLOWED-HOSTS"]),
R("REQ-017","HTTPS redirect enabled","Transport","Medium",
  desc="HTTP requests must be redirected to HTTPS in production (SECURE_SSL_REDIRECT or equivalent proxy rule).",
  fix="Enable SECURE_SSL_REDIRECT or enforce the redirect at the load balancer/reverse proxy.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-319"],owasp="A02:2021",
  conf=["CFG-SSL-REDIRECT"]),
R("REQ-018","Secure session cookie","Session","Medium",
  desc="SESSION_COOKIE_SECURE must be set so the session cookie is only sent over HTTPS.",
  fix="Set SESSION_COOKIE_SECURE = True in production settings.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-614"],owasp="A05:2021",
  conf=["CFG-SESS-SECURE"],dast=["DAST-COOKIE-FLAGS"]),
R("REQ-019","Secure CSRF cookie","CSRF","Medium",
  desc="CSRF_COOKIE_SECURE must be set so the CSRF cookie is only sent over HTTPS.",
  fix="Set CSRF_COOKIE_SECURE = True in production settings.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-614"],owasp="A05:2021",
  conf=["CFG-CSRF-SECURE"]),
R("REQ-020","HSTS configured","Headers","Medium",
  desc="HTTP Strict-Transport-Security must be enabled with a sensible max-age (and includeSubDomains where appropriate).",
  fix="Set SECURE_HSTS_SECONDS >= 31536000 with SECURE_HSTS_INCLUDE_SUBDOMAINS after confirming HTTPS everywhere.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-523"],owasp="A05:2021",
  conf=["CFG-HSTS"],dast=["DAST-HDR-HSTS"]),
R("REQ-021","Content-type sniffing disabled","Headers","Low",
  desc="X-Content-Type-Options: nosniff must be set to prevent MIME sniffing attacks.",
  fix="Enable SECURE_CONTENT_TYPE_NOSNIFF (on by default) and keep SecurityMiddleware active.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-16"],owasp="A05:2021",
  conf=["CFG-NOSNIFF"],dast=["DAST-HDR-NOSNIFF"]),
R("REQ-022","Clickjacking protection","Headers","Low",
  desc="X-Frame-Options or CSP frame-ancestors must prevent the site from being framed by untrusted origins.",
  fix="Keep XFrameOptionsMiddleware enabled / set X_FRAME_OPTIONS=DENY or a restrictive frame-ancestors CSP.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-1021"],owasp="A05:2021",
  conf=["CFG-XFO"],dast=["DAST-HDR-XFO"]),
R("REQ-023","Session cookie HttpOnly","Session","Medium",
  desc="SESSION_COOKIE_HTTPONLY must be set so JavaScript cannot read the session cookie.",
  fix="Set SESSION_COOKIE_HTTPONLY = True (default) and verify no JS depends on the session cookie.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-1004"],owasp="A05:2021",
  conf=["CFG-SESS-HTTPONLY"],dast=["DAST-COOKIE-FLAGS"]),
R("REQ-024","CSRF cookie HttpOnly reviewed for architecture","CSRF","Low",
  desc="CSRF_COOKIE_HTTPONLY should be reviewed: if the token is only needed in forms it should be HttpOnly; SPA architectures may need JS access with compensating controls.",
  fix="Set CSRF_COOKIE_HTTPONLY=True unless a documented SPA requirement exists; then scope and rotate the token.",
  ver=["configuration"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-1004"],owasp="A05:2021",
  conf=["CFG-CSRF-HTTPONLY"]),
R("REQ-025","Session expiry/invalidation","Session","Medium",
  desc="Sessions must expire after a reasonable idle/absolute lifetime and be invalidated on privilege change.",
  fix="Set SESSION_COOKIE_AGE appropriately, rotate sessions on login/permission change, and expire idle sessions.",
  ver=["configuration","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-613"],owasp="A07:2021",
  conf=["CFG-SESS-AGE"],manual=True),
R("REQ-026","Session fixation protection","Session","Medium",
  desc="Session identifiers must be rotated at login so a pre-fixated session id cannot be reused after authentication.",
  fix="Use Django auth views (they call session.cycle_key()); verify custom login flows rotate the session key.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-384"],owasp="A07:2021",manual=True),
R("REQ-027","Safe XSS output encoding","XSS","High",
  desc="Templates must autoescape output; |safe, autoescape off and raw HTML injection paths must not render untrusted data.",
  fix="Keep autoescaping on, avoid |safe/autoescape-off on user data, and sanitize any HTML that must be rendered.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-79"],owasp="A03:2021",
  sast=["XSS-002","XSS-003"],dast=["DAST-XSS-001"],tests=["XSS-001"]),
R("REQ-028","mark_safe only for trusted/sanitized content","XSS","High",
  desc="mark_safe()/format_html must only ever receive trusted or sanitized content, never request-controlled data.",
  fix="Remove mark_safe on dynamic data; use format_html or sanitize with an allowlist-based sanitizer.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-79"],owasp="A03:2021",
  sast=["XSS-001"]),
R("REQ-029","No unsafe eval/exec/compile","Input Validation","Critical",
  desc="eval(), exec(), compile() and dynamic __import__() must not be used, especially with externally influenced input.",
  fix="Remove dynamic code execution; use explicit dispatch tables or ast.literal_eval for data literals.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-95"],owasp="A03:2021",
  sast=["DYN-001","DYN-002"]),
R("REQ-030","No unsafe pickle/YAML deserialization","Input Validation","High",
  desc="pickle/marshal deserialization and yaml.load without SafeLoader can lead to remote code execution on untrusted data.",
  fix="Use yaml.safe_load, avoid pickle for untrusted data, prefer JSON with strict schema validation.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-502"],owasp="A08:2021",
  sast=["DESER-001","DESER-002","DESER-003"]),
R("REQ-031","Safe OS command execution","Input Validation","Critical",
  desc="os.system/os.popen and subprocess with shell=True or user-controlled arguments enable command injection.",
  fix="Use subprocess with argument lists (shell=False), validate arguments against an allowlist, avoid shell syntax.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-78"],owasp="A03:2021",
  sast=["CMD-001","CMD-002","CMD-003"]),
R("REQ-032","Path traversal prevention","File Security","High",
  desc="File paths derived from user input must be confined (no ../ escape) before open/read/write/send.",
  fix="Resolve paths against a fixed base and verify with os.path.commonpath; reject out-of-base results.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-22"],owasp="A01:2021",
  sast=["PATH-001","PATH-002"],dast=["DAST-TRAVERSAL-001"],tests=["TRAVERSAL-001"]),
R("REQ-033","Uploaded file type/size validation","File Security","Medium",
  desc="Uploads must be validated for real content type, size limits and safe filenames before storage.",
  fix="Validate MIME by content inspection, enforce size limits, sanitize filenames and store outside code paths.",
  ver=["sast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-434"],owasp="A04:2021",
  sast=["UPLOAD-001"],manual=True),
R("REQ-034","Uploads cannot execute server-side code","File Security","High",
  desc="Upload storage must not allow server-side execution (no uploads inside code dirs/templates, no executable interpreters on media paths).",
  fix="Serve media from a separate domain/bucket with no-code-execution configuration and restrictive permissions.",
  ver=["manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-94"],owasp="A04:2021",manual=True),
R("REQ-035","Secure temporary-file handling","File Security","Low",
  desc="Temporary files must be created securely (no predictable names via tempfile.mktemp).",
  fix="Use tempfile.mkstemp/mkdtemp or NamedTemporaryFile; never mktemp.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-377"],owasp="A05:2021",
  sast=["TMP-001"]),
R("REQ-036","No arbitrary filesystem reads","File Security","High",
  desc="Views must not read/serve arbitrary filesystem paths based on request parameters.",
  fix="Map request parameters to allowlisted identifiers; never pass user input directly to open()/sendfile().",
  ver=["sast","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-73"],owasp="A01:2021",
  sast=["PATH-001","PATH-002"],tests=["TRAVERSAL-001"]),
R("REQ-037","SSRF destination validation","Input Validation","High",
  desc="Server-side HTTP requests whose URL derives from user input must validate the destination (scheme/host allowlist, no internal ranges).",
  fix="Allowlist schemes and hosts, resolve DNS and block private/link-local ranges before fetching.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-918"],owasp="A10:2021",
  sast=["SSRF-001"],dast=["DAST-SSRF-001"],tests=["SSRF-001"]),
R("REQ-038","Open-redirect prevention","HTTP/Web","Medium",
  desc="Redirect targets taken from input must be validated against an allowlist to prevent phishing via open redirects.",
  fix="Use url_has_allowed_host_and_scheme() or redirect by name/id instead of raw URLs.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-601"],owasp="A01:2021",
  sast=["REDIR-001"],dast=["DAST-REDIR-001"],tests=["REDIR-001"]),
R("REQ-039","CORS restricted to trusted origins","HTTP/Web","Medium",
  desc="CORS configuration must not use wildcard origins (especially with credentials) and must list only trusted origins.",
  fix="Enumerate exact origins in CORS_ALLOWED_ORIGINS; never combine CORS_ALLOW_ALL_ORIGINS with credentialed requests.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-942"],owasp="A05:2021",
  conf=["CFG-CORS"]),
R("REQ-040","CSRF trusted origins explicit","CSRF","Medium",
  desc="CSRF_TRUSTED_ORIGINS must be explicit and limited to real deployment origins (no wildcards on schemes).",
  fix="List exact https origins in CSRF_TRUSTED_ORIGINS matching the deployment.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-352"],owasp="A05:2021",
  conf=["CFG-CSRF-ORIGINS"]),
R("REQ-041","Raw SQL reviewed","Database","High",
  desc="Every use of raw(), extra(), RawSQL or cursor.execute must be reviewed and parameterized.",
  fix="Centralize raw SQL, parameterize it, and document the review of each occurrence.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-89"],owasp="A03:2021",
  sast=["SQLI-001","SQLI-002","SQLI-003","SQLI-004"]),
R("REQ-042","Database credentials securely stored","Database","Medium",
  desc="DATABASES credentials must come from environment/secret manager, not hardcoded in settings.",
  fix="Reference os.environ for DB user/password and rotate any committed credentials.",
  ver=["configuration","sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-259"],owasp="A05:2021",
  conf=["CFG-DB-CREDS"],sast=["SECRET-002"]),
R("REQ-043","Database least privilege","Database","Medium",
  desc="The application database account must have only the privileges it needs (no superuser, no DDL in runtime).",
  fix="Create a dedicated role with table-level grants; keep migrations on a separate privileged role.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-250"],owasp="A05:2021",manual=True),
R("REQ-044","Sensitive data excluded from API responses","API","High",
  desc="Serializers and views must not return passwords, tokens, PII or internal fields that clients do not need.",
  fix="Whitelist serializer fields, mark sensitive fields write_only/read_only, and review responses.",
  ver=["sast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-200"],owasp="A01:2021",
  sast=["SENSITIVE-001"],manual=True),
R("REQ-045","DRF authentication classes defined","API","High",
  desc="REST framework must define explicit authentication classes globally and per-view.",
  fix="Set DEFAULT_AUTHENTICATION_CLASSES and review views that deviate from it.",
  ver=["configuration","sast"],auto="FULLY_AUTOMATED",cwe=["CWE-306"],owasp="A07:2021",
  conf=["CFG-DRF-AUTH"],sast=["AUTHZ-003"]),
R("REQ-046","DRF permission classes defined","API","High",
  desc="REST framework must define explicit default permission classes; implicit AllowAny is unsafe.",
  fix="Set DEFAULT_PERMISSION_CLASSES=IsAuthenticated (or stricter) and justify every exception.",
  ver=["configuration","sast"],auto="FULLY_AUTOMATED",cwe=["CWE-862"],owasp="A01:2021",
  conf=["CFG-DRF-PERM"],sast=["AUTHZ-002"]),
R("REQ-047","AllowAny explicitly justified","API","Medium",
  desc="Every AllowAny usage must be intentional, documented and limited to genuinely public endpoints.",
  fix="Replace AllowAny with explicit anonymous-view markers and document the justification per endpoint.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-284"],owasp="A01:2021",
  sast=["AUTHZ-001"]),
R("REQ-048","DRF object-level permissions","API","High",
  desc="Detail endpoints must enforce object-level authorization (get_queryset scoping and/or per-object permission checks).",
  fix="Scope get_queryset to the requesting user/tenant and add object permission checks on mutation.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  sast=["AUTHZ-OBJECT-001"],dast=["DAST-IDOR-001"],tests=["IDOR-001"]),
R("REQ-049","API throttling where appropriate","API","Medium",
  desc="Public or expensive API endpoints must be throttled to limit abuse and DoS.",
  fix="Configure DEFAULT_THROTTLE_CLASSES/RATES (and per-view throttles) for anonymous and user scopes.",
  ver=["configuration"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-770"],owasp="A04:2021",
  conf=["CFG-THROTTLE"]),
R("REQ-050","HTTP methods restricted","HTTP/Web","Low",
  desc="Views must accept only the HTTP methods they implement; unused methods should be rejected.",
  fix="Set http_method_names explicitly and use @api_view with the exact method list.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-749"],owasp="A05:2021",
  sast=["METHOD-001"]),
R("REQ-051","Strict DRF serializer validation","API","Medium",
  desc="Write endpoints must validate input through serializers; raw request.data must not be spread into models.",
  fix="Always bind request data through a serializer and call is_valid(raise_exception=True) before saving.",
  ver=["sast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-20"],owasp="A03:2021",
  sast=["SER-001","MASS-001"],manual=True),
R("REQ-052","API pagination/result limits","API","Low",
  desc="List endpoints must paginate with a bounded page size to prevent unbounded result extraction.",
  fix="Set DEFAULT_PAGINATION_CLASS with a small PAGE_SIZE and forbid unlimited queries.",
  ver=["configuration"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-770"],owasp="A04:2021",
  conf=["CFG-PAGINATION"]),
R("REQ-053","Safe API error messages","API","Low",
  desc="API errors must not leak stack traces, settings, SQL or internal paths.",
  fix="Use DRF exception handling, keep DEBUG=False and customize error payloads.",
  ver=["configuration","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-209"],owasp="A05:2021",
  conf=["CFG-DEBUG"],dast=["DAST-DEBUG-001"]),
R("REQ-054","Django admin appropriately restricted","Authorization","Medium",
  desc="The admin must not be anonymously accessible, should be network-protected, and must not expose sensitive models to non-staff.",
  fix="Keep admin behind authentication, add IP allowlisting/VPN, and audit ModelAdmin permissions.",
  ver=["dast","automated","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-862"],owasp="A01:2021",
  dast=["DAST-ADMIN-001"],tests=["AUTHZ-V-001"],manual=True),
R("REQ-055","Security-sensitive actions auditable","Logging","Medium",
  desc="Privileged and security-sensitive actions must be logged with actor, target and outcome.",
  fix="Add audit logging (django-auditlog or custom) for admin, permission and data-export actions.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-778"],owasp="A09:2021",manual=True),
R("REQ-056","Secrets/passwords excluded from logs","Logging","Medium",
  desc="Logs must never contain passwords, tokens, session ids or PII.",
  fix="Filter sensitive fields in log formatters and review log statements that include request data.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-532"],owasp="A09:2021",
  sast=["LOG-001"]),
R("REQ-057","Log injection prevention","Logging","Low",
  desc="User input written to logs must be sanitized to prevent log forging/CRLF injection.",
  fix="Strip newlines/control chars from logged user input or use structured logging.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-117"],owasp="A09:2021",
  sast=["LOG-002"]),
R("REQ-058","Security-event monitoring","Logging","Medium",
  desc="Security events (failed logins, permission denials, config changes) must be monitored and alerted on.",
  fix="Ship security logs to a SIEM/monitoring stack with alert rules for anomalies.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-778"],owasp="A09:2021",manual=True),
R("REQ-059","Dependencies controlled/pinned","Dependencies","Medium",
  desc="Dependencies must be declared in lock/pin files; floating installs make builds unreproducible and unsafe.",
  fix="Pin direct dependencies (or use a lockfile via pip-tools/poetry) and review upgrades deliberately.",
  ver=["dependencies"],auto="FULLY_AUTOMATED",cwe=["CWE-1104"],owasp="A06:2021",
  dep=["DEP-PIN-001"]),
R("REQ-060","Dependencies checked for known vulnerabilities","Dependencies","High",
  desc="All dependencies must be checked against vulnerability advisories (CVE/GHSA) and vulnerable versions upgraded.",
  fix="Run pip-audit/safety/Dependabot in CI and upgrade packages with known CVEs.",
  ver=["dependencies"],auto="FULLY_AUTOMATED",cwe=["CWE-1395"],owasp="A06:2021",
  dep=["DEP-CVE-001"]),
R("REQ-061","Outdated dependencies reviewed","Dependencies","Low",
  desc="Materially outdated dependencies (especially security-critical ones) must be reviewed and updated.",
  fix="Schedule dependency refresh reviews; prioritize Django, cryptography and auth-related packages.",
  ver=["dependencies"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-1104"],owasp="A06:2021",
  dep=["DEP-OLD-001"]),
R("REQ-062","No MD5/SHA1 for security purposes","Cryptography","Medium",
  desc="MD5/SHA1 must not be used for signatures, tokens, password hashing or integrity where security matters.",
  fix="Use SHA-256+/HMAC-SHA256 or better; keep MD5 only for non-security checksums with a comment.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-328"],owasp="A02:2021",
  sast=["CRYPTO-001"]),
R("REQ-063","Approved modern cryptography","Cryptography","Medium",
  desc="Cryptographic algorithms and modes must be current standards (no DES/ECB/home-grown crypto).",
  fix="Use vetted libraries (cryptography, PyNaCl) with approved algorithms and modes.",
  ver=["sast","dependencies"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-327"],owasp="A02:2021",
  sast=["CRYPTO-004"],dep=["DEP-CVE-001"]),
R("REQ-064","Cryptographic keys securely managed","Cryptography","High",
  desc="Keys must be generated securely, stored in secret managers/KMS, rotated, and never hardcoded.",
  fix="Move key material to KMS/secret manager, rotate exposed keys, and use secrets.token_bytes for generation.",
  ver=["sast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-321"],owasp="A02:2021",
  sast=["SECRET-007","CRYPTO-002"],manual=True),
R("REQ-065","TLS for sensitive traffic","Transport","High",
  desc="All sensitive traffic (internal service-to-service included) must use TLS with valid configuration.",
  fix="Enable TLS end-to-end, verify certificates, and disable plaintext fallbacks for sensitive flows.",
  ver=["configuration","network","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-319"],owasp="A02:2021",
  conf=["CFG-SSL-REDIRECT","CFG-HSTS"],net=["PORT-TLS-001"],manual=True),
R("REQ-066","Sensitive data protected at rest","Cryptography","Medium",
  desc="Sensitive data at rest (DB, backups, object storage) must be encrypted or otherwise protected.",
  fix="Enable disk/DB encryption, encrypt backups, and control key access.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-311"],owasp="A02:2021",manual=True),
R("REQ-067","Security headers consistently configured","Headers","Medium",
  desc="Security headers must be present and consistent across all responses (not only some routes).",
  fix="Centralize headers via SecurityMiddleware/proxy config and verify all response types.",
  ver=["configuration","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-693"],owasp="A05:2021",
  conf=["CFG-NOSNIFF","CFG-XFO","CFG-HSTS","CFG-REFERRER"],dast=["DAST-HDR-HSTS","DAST-HDR-NOSNIFF","DAST-HDR-XFO"]),
R("REQ-068","Content Security Policy evaluated","Headers","Low",
  desc="A Content-Security-Policy appropriate to the application's needs should be deployed or explicitly justified.",
  fix="Deploy django-csp or proxy-level CSP starting in report-only mode, then enforce.",
  ver=["configuration","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-693"],owasp="A05:2021",
  conf=["CFG-CSP"],dast=["DAST-HDR-CSP"]),
R("REQ-069","Restrictive Referrer-Policy","Headers","Low",
  desc="Referrer-Policy must limit referrer leakage (same-origin, strict-origin-when-cross-origin or stricter).",
  fix="Set SECURE_REFERRER_POLICY to same-origin or strict-origin-when-cross-origin.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-200"],owasp="A05:2021",
  conf=["CFG-REFERRER"],dast=["DAST-HDR-REFERRER"]),
R("REQ-070","Restrictive Permissions-Policy","Headers","Low",
  desc="Permissions-Policy should disable unused browser features (camera, geolocation, etc.).",
  fix="Add a Permissions-Policy header denying features the app does not use.",
  ver=["dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-200"],owasp="A05:2021",
  dast=["DAST-HDR-PERMPOL"]),
]
