"""Requirement catalogue part 2: REQ-071 .. REQ-137."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from reqcommon import R  # noqa: E402

REQS2 = [
R("REQ-071","Frontend controls never replace server authorization","Business Logic","High",
  desc="UI hiding/disabling of actions must never be the only enforcement; the server must re-check authorization.",
  fix="Verify every sensitive action has a server-side permission check independent of frontend state.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-602"],owasp="A04:2021",manual=True),
R("REQ-072","Workflow/state transitions authorization-controlled","Business Logic","High",
  desc="State machines (orders, approvals, tickets) must validate allowed transitions and the actor's right to trigger them.",
  fix="Model transitions explicitly and check permissions on each transition, server-side.",
  ver=["manual","dast"],auto="MANUAL",cwe=["CWE-841"],owasp="A04:2021",manual=True),
R("REQ-073","Mass assignment prevented","Business Logic","High",
  desc="Model updates must not blindly accept arbitrary fields from request data (**request.data, fields='__all__' writes).",
  fix="Whitelist writable serializer fields and never spread request data into model constructors.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-915"],owasp="A04:2021",
  sast=["MASS-001","SER-001"]),
R("REQ-074","Race-sensitive operations made atomic","Business Logic","Medium",
  desc="Read-modify-write operations (balances, counters, quotas) must use atomic constructs to avoid race conditions.",
  fix="Use F() expressions, select_for_update() or transaction.atomic() around sensitive updates.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-362"],owasp="A04:2021",
  sast=["RACE-001"]),
R("REQ-075","Expensive operations rate-limited","Availability","Medium",
  desc="Expensive endpoints (search, export, email, report generation) must be rate limited per user/IP.",
  fix="Apply DRF throttles or django-ratelimit to expensive views with sane limits.",
  ver=["configuration","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-400"],owasp="A04:2021",
  conf=["CFG-THROTTLE"],manual=True),
R("REQ-076","Request/body/upload size limits","Availability","Medium",
  desc="Request bodies and uploads must have explicit size limits to prevent resource exhaustion.",
  fix="Set DATA_UPLOAD_MAX_MEMORY_SIZE, FILE_UPLOAD_MAX_MEMORY_SIZE and proxy-level client_max_body_size.",
  ver=["configuration"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-770"],owasp="A05:2021",
  conf=["CFG-BODY-LIMIT"]),
R("REQ-077","Regex denial-of-service prevention","Availability","Low",
  desc="Regular expressions (especially on user input) must avoid catastrophic backtracking patterns.",
  fix="Simplify nested quantifiers, bound input length, and test expensive patterns with long inputs.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-1333"],owasp="A03:2021",
  sast=["DOS-001"]),
R("REQ-078","Server-side template injection prevention","Input Validation","Critical",
  desc="Template sources must never be built from user input (Template(user_str), from_string with request data).",
  fix="Render only code-defined templates with user data as context, never user data as template source.",
  ver=["sast","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-1336"],owasp="A03:2021",
  sast=["TPL-001"],dast=["DAST-XSS-001"]),
R("REQ-079","Unsafe XML external entities prevented","Input Validation","Medium",
  desc="XML parsing must disable external entity resolution (use defusedxml or hardened parsers).",
  fix="Use defusedxml for all untrusted XML parsing; disable entity expansion in lxml.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-611"],owasp="A05:2021",
  sast=["XXE-001"]),
R("REQ-080","Safe JSON/YAML parsing","Input Validation","Medium",
  desc="YAML must be parsed with safe_load; JSON parsing must be standard-library/json-based with schema validation.",
  fix="Replace yaml.load with yaml.safe_load and validate JSON structure after parsing.",
  ver=["sast"],auto="FULLY_AUTOMATED",cwe=["CWE-502"],owasp="A08:2021",
  sast=["DESER-002"]),
R("REQ-081","URL schemes allowlisted","Input Validation","Medium",
  desc="User-supplied URLs must be restricted to allowed schemes (no javascript:/data: in redirects or stored links).",
  fix="Validate schemes against an allowlist (https/http) before use in redirects or rendered links.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-601"],owasp="A01:2021",
  sast=["REDIR-001"]),
R("REQ-082","No production stack traces","Information Disclosure","High",
  desc="Production responses must never expose Django debug stack traces or technical error pages.",
  fix="Keep DEBUG=False, configure proper 500/404 handlers and centralized exception handling.",
  ver=["configuration","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-209"],owasp="A05:2021",
  conf=["CFG-DEBUG"],dast=["DAST-DEBUG-001"]),
R("REQ-083","Debug/source artifacts not exposed","Information Disclosure","Medium",
  desc="Source files, backups, .bak/.old copies and debug artifacts must not be web-accessible.",
  fix="Configure the web server to deny dotfiles/backups and keep source out of the document root.",
  ver=["dast"],auto="FULLY_AUTOMATED",cwe=["CWE-530"],owasp="A05:2021",
  dast=["DAST-ENV-001"]),
R("REQ-084",".env/config secrets not web-accessible","Information Disclosure","High",
  desc=".env and config files must never be served by the web server.",
  fix="Deny dotfile access at the proxy and keep .env outside static/media roots.",
  ver=["dast"],auto="FULLY_AUTOMATED",cwe=["CWE-538"],owasp="A05:2021",
  dast=["DAST-ENV-001"]),
R("REQ-085",".git metadata not web-accessible","Information Disclosure","High",
  desc=".git directories must not be reachable over HTTP (full repository disclosure).",
  fix="Deny /.git access at the proxy and never deploy the repository directory as the document root.",
  ver=["dast"],auto="FULLY_AUTOMATED",cwe=["CWE-538"],owasp="A05:2021",
  dast=["DAST-ENV-001"]),
R("REQ-086","Static/media storage permissions restrictive","File Security","Low",
  desc="Static/media storage directories and buckets must use restrictive permissions and no public-write.",
  fix="Apply least-privilege ACLs on storage; forbid public-write on media buckets.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-732"],owasp="A01:2021",manual=True),
R("REQ-087","Sensitive file downloads authorized","Authorization","High",
  desc="File/download endpoints must check the requester's right to access each file before streaming it.",
  fix="Authorize the underlying object before FileResponse/sendfile and avoid predictable file URLs.",
  ver=["sast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-862"],owasp="A01:2021",
  sast=["PATH-002"],manual=True),
R("REQ-088","Object IDs do not bypass authorization","Authorization","High",
  desc="Guessing/enumerating object IDs must not grant access; authorization must not rely on ID secrecy.",
  fix="Always authorize the fetched object for the requester; consider UUIDs only as obscurity, not control.",
  ver=["dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  dast=["DAST-IDOR-001"],tests=["IDOR-001"]),
R("REQ-089","Password-reset tokens expire and are single-use","Authentication","Medium",
  desc="Password reset tokens must expire quickly and be invalidated after first use.",
  fix="Use Django's PasswordResetTokenGenerator defaults (3-day, single-use) or stricter custom generator.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-640"],owasp="A07:2021",manual=True),
R("REQ-090","Verification tokens expire and are single-use","Authentication","Medium",
  desc="Email/phone verification tokens must expire and be single-use with attempt limiting.",
  fix="Issue short-lived signed tokens (django.core.signing with max_age) and invalidate on use.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-640"],owasp="A07:2021",manual=True),
R("REQ-091","MFA for privileged accounts where required","Authentication","Medium",
  desc="Administrative/privileged accounts should use MFA where the risk profile requires it.",
  fix="Integrate TOTP/WebAuthn MFA (django-otp/django-allauth MFA) for staff accounts.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-308"],owasp="A07:2021",manual=True),
R("REQ-092","Account enumeration minimized","Authentication","Low",
  desc="Login/reset flows must not reveal whether an account exists via messages, timing or side channels.",
  fix="Use uniform messages and flows for existing/non-existing accounts and add rate limiting.",
  ver=["dast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-204"],owasp="A07:2021",
  dast=["DAST-ENUM-001"],manual=True),
R("REQ-093","Safe authentication failure handling","Authentication","Low",
  desc="Failed authentication must return generic errors without leaking internal state or stack traces.",
  fix="Return uniform 401/403 responses and log failures server-side only.",
  ver=["dast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-209"],owasp="A07:2021",
  dast=["DAST-DEBUG-001"],manual=True),
R("REQ-094","Logout invalidates session/token","Session","Medium",
  desc="Logout must invalidate the session server-side (and refresh/API tokens where used).",
  fix="Use Django logout (flushes session); maintain a token denylist or short-lived tokens for APIs.",
  ver=["dast","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-613"],owasp="A07:2021",
  dast=["DAST-SESS-001"],manual=True),
R("REQ-095","Authorization checked on every sensitive operation","Authorization","High",
  desc="Every create/update/delete/export action must re-check authorization; one central check is not enough.",
  fix="Add permission checks per view/action and cover them with authorization tests.",
  ver=["sast","dast","automated"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-862"],owasp="A01:2021",
  sast=["AUTHZ-002"],dast=["DAST-AUTHZ-001"],tests=["AUTHZ-V-001"]),
R("REQ-096","Querysets scoped to authorized user/tenant","Authorization","High",
  desc="Querysets backing views/APIs must be filtered to the requesting user or tenant.",
  fix="Override get_queryset to filter by request.user/tenant; never expose Model.objects.all() directly.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  sast=["AUTHZ-OBJECT-001"]),
R("REQ-097","Background jobs preserve tenant/security context","Multi-tenant","Medium",
  desc="Async/background jobs must carry and respect tenant and permission context instead of running as implicit superuser.",
  fix="Pass explicit tenant/user context into tasks and re-check permissions inside the task.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-639"],owasp="A04:2021",manual=True),
R("REQ-098","Scheduled/admin jobs use least privilege","Authorization","Medium",
  desc="Cron/management jobs must run with least-privilege credentials, not database or service superusers.",
  fix="Give scheduled jobs dedicated low-privilege credentials scoped to their data needs.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-250"],owasp="A05:2021",manual=True),
R("REQ-099","Security-impacting migrations reviewed","Database","Low",
  desc="Migrations changing permissions, fields with sensitive data, or access patterns must be security-reviewed.",
  fix="Add a security review checklist item for migrations touching auth, PII or permissions.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-284"],owasp="A04:2021",manual=True),
R("REQ-100","Sensitive fields controlled in serializers","API","High",
  desc="Serializers must explicitly control sensitive fields (write_only for secrets, excluded internals).",
  fix="Mark password/token fields write_only and exclude internal fields from serializer Meta.fields.",
  ver=["sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-200"],owasp="A01:2021",
  sast=["SENSITIVE-001"]),
R("REQ-101","PII access auditable","Privacy","Medium",
  desc="Access to personal data must be logged/auditable to support accountability and breach investigation.",
  fix="Log PII read/export with actor and purpose; restrict PII endpoints to need-to-know roles.",
  ver=["manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-778"],owasp="A09:2021",manual=True),
R("REQ-102","Data retention/deletion enforced","Privacy","Medium",
  desc="Retention periods must be defined and enforced; deletion requests must remove data including backups within policy.",
  fix="Implement retention jobs and verified deletion workflows including backup rotation policy.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-212"],owasp="A04:2021",manual=True),
R("REQ-103","Backups access-controlled","Privacy","Medium",
  desc="Backups must be access-controlled, encrypted and restored-tested.",
  fix="Restrict backup access, encrypt archives, and schedule restore tests.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-921"],owasp="A04:2021",manual=True),
R("REQ-104","Production settings avoid development defaults","Configuration","High",
  desc="Production settings modules must not inherit development defaults (DEBUG, dev hosts, dev credentials).",
  fix="Separate base/dev/prod settings; production must set secure values explicitly and fail on insecure defaults.",
  ver=["configuration"],auto="FULLY_AUTOMATED",cwe=["CWE-1188"],owasp="A05:2021",
  conf=["CFG-DEBUG","CFG-ALLOWED-HOSTS","CFG-DB-CREDS"]),
R("REQ-105","Reverse-proxy/security header configuration reviewed","Infrastructure","Low",
  desc="Proxy configuration (SECURE_PROXY_SSL_HEADER, forwarded headers, header overrides) must match the actual deployment.",
  fix="Document the proxy topology and verify SECURE_PROXY_SSL_HEADER is only set behind a trusted proxy.",
  ver=["configuration","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-16"],owasp="A05:2021",
  conf=["CFG-PROXY-SSL"],manual=True),
R("REQ-106","Host/origin configuration matches deployment","Configuration","Medium",
  desc="ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS and CORS origins must exactly match real deployment domains.",
  fix="Reconcile host/origin settings with the deployment inventory at every release.",
  ver=["configuration","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-16"],owasp="A05:2021",
  conf=["CFG-ALLOWED-HOSTS","CFG-CSRF-ORIGINS","CFG-CORS"],manual=True),
R("REQ-107","DB/cache/broker ports not publicly exposed","Network","High",
  desc="Database, cache and message-broker ports (5432/3306/6379/11211/5672/27017...) must not be reachable outside the trusted network.",
  fix="Bind backing services to internal networks, firewall them, and use private endpoints.",
  ver=["network"],auto="FULLY_AUTOMATED",cwe=["CWE-668"],owasp="A05:2021",
  net=["PORT-DB-001","PORT-CACHE-001"]),
R("REQ-108","Unnecessary network ports closed","Network","Medium",
  desc="Only required service ports should be open; everything else must be closed or filtered.",
  fix="Inventory open ports, justify each, and close or firewall the rest.",
  ver=["network"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-668"],owasp="A05:2021",
  net=["PORT-EXTRA-001"]),
R("REQ-109","Insecure legacy services not exposed","Network","High",
  desc="Cleartext/legacy services (Telnet, FTP, rlogin) must not be exposed.",
  fix="Replace Telnet/FTP with SSH/SFTP and remove legacy daemons.",
  ver=["network"],auto="FULLY_AUTOMATED",cwe=["CWE-319"],owasp="A05:2021",
  net=["PORT-TELNET-001","PORT-FTP-001"]),
R("REQ-110","SSH securely configured","Network","Medium",
  desc="SSH must run a current version with key-based auth, no root login and no weak algorithms.",
  fix="Harden sshd_config (no passwords, no root, modern KEX/ciphers) and keep OpenSSH updated.",
  ver=["network","manual"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-287"],owasp="A05:2021",
  net=["PORT-SSH-001"],manual=True),
R("REQ-111","Network service versions inventoried","Network","Low",
  desc="All exposed services and versions must be inventoried and tracked for vulnerabilities.",
  fix="Maintain a service inventory from scan results and feed versions into vulnerability tracking.",
  ver=["network"],auto="FULLY_AUTOMATED",cwe=["CWE-200"],owasp="A05:2021",
  net=["SVC-VERSION-001"]),
R("REQ-112","Django development server not publicly exposed","Network","High",
  desc="manage.py runserver (development server) must never be reachable beyond localhost/dev environments.",
  fix="Serve production via gunicorn/uwsgi behind a proxy; block external access to dev ports.",
  ver=["network","configuration"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-489"],owasp="A05:2021",
  net=["PORT-DEVSRV-001"],conf=["CFG-DEBUG"]),
R("REQ-113","TLS services use secure protocols","Transport","Medium",
  desc="TLS endpoints must use TLS 1.2+ with strong cipher configuration.",
  fix="Disable TLS<1.2 and weak ciphers on all TLS-terminating services.",
  ver=["network"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-326"],owasp="A02:2021",
  net=["PORT-TLS-001"]),
R("REQ-114","Default service credentials removed","Infrastructure","High",
  desc="Default credentials of installed services (admin/admin, postgres defaults) must be changed or removed.",
  fix="Change all vendor default credentials during provisioning and verify in hardening checklists.",
  ver=["manual","sast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-1393"],owasp="A05:2021",
  sast=["SECRET-002"],manual=True),
R("REQ-115","Network service segmentation","Network","Medium",
  desc="Tiers (web, app, data) must be segmented so a web compromise does not give direct data-tier access.",
  fix="Use subnets/security groups to enforce tier-to-tier least-privilege paths.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-668"],owasp="A05:2021",manual=True),
R("REQ-116","Firewall least privilege","Network","Medium",
  desc="Firewall/security-group rules must allow only required flows and be reviewed regularly.",
  fix="Default-deny inbound, allow only documented flows, and review rules quarterly.",
  ver=["manual"],auto="MANUAL",cwe=["CWE-284"],owasp="A05:2021",manual=True),
R("REQ-117","Health/debug endpoints protected","Information Disclosure","Medium",
  desc="Health/status/debug endpoints must not leak versions, settings or internals to unauthenticated callers.",
  fix="Return minimal liveness data publicly; gate detailed status endpoints behind auth/network controls.",
  ver=["dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-200"],owasp="A05:2021",
  dast=["DAST-HEALTH-001"]),
R("REQ-118","API documentation exposure controlled","Information Disclosure","Low",
  desc="Swagger/Redoc/OpenAPI docs must not be publicly exposed in production unless intended.",
  fix="Disable or auth-gate schema/docs endpoints outside development.",
  ver=["dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-200"],owasp="A05:2021",
  dast=["DAST-DOCS-001"]),
R("REQ-119","Authentication-bypass security tests","Testing","High",
  desc="The audit must execute tests attempting to bypass authentication on protected endpoints.",
  fix="Keep these automated tests in CI; fix any endpoint reachable without credentials.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-306"],owasp="A07:2021",
  tests=["AUTH-001"],dast=["DAST-AUTH-001"]),
R("REQ-120","Horizontal privilege-escalation tests","Testing","High",
  desc="The audit must execute tests where a user attempts to access/modify another user's resources.",
  fix="Fix any endpoint returning another user's data; add object-level authorization.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  tests=["AUTHZ-H-001"],dast=["DAST-IDOR-001"]),
R("REQ-121","Vertical privilege-escalation tests","Testing","High",
  desc="The audit must execute tests where a normal user attempts admin/privileged operations.",
  fix="Fix any privileged action reachable by non-privileged roles.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-269"],owasp="A01:2021",
  tests=["AUTHZ-V-001"],dast=["DAST-ADMIN-001"]),
R("REQ-122","XSS security tests","Testing","High",
  desc="The audit must execute reflected/stored XSS probes against input-bearing endpoints.",
  fix="Encode output, sanitize HTML, and fix every reflected payload.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-79"],owasp="A03:2021",
  tests=["XSS-001"],dast=["DAST-XSS-001"]),
R("REQ-123","SQL-injection security tests","Testing","Critical",
  desc="The audit must execute SQL injection probes (error-based and boolean heuristics) against query-bearing endpoints.",
  fix="Parameterize all queries; fix any endpoint showing SQL errors or injection behaviour.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-89"],owasp="A03:2021",
  tests=["SQLI-001"],dast=["DAST-SQLI-001"]),
R("REQ-124","SSRF security tests","Testing","High",
  desc="The audit must execute SSRF probes on endpoints accepting URLs/hostnames.",
  fix="Validate destinations against an allowlist and block internal ranges.",
  ver=["automated","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-918"],owasp="A10:2021",
  tests=["SSRF-001"],dast=["DAST-SSRF-001"]),
R("REQ-125","Path-traversal security tests","Testing","High",
  desc="The audit must execute path traversal probes against file-serving endpoints and parameters.",
  fix="Confine file access to a base directory and reject traversal sequences.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-22"],owasp="A01:2021",
  tests=["TRAVERSAL-001"],dast=["DAST-TRAVERSAL-001"]),
R("REQ-126","Unsafe-file-upload security tests","Testing","High",
  desc="The audit must execute upload tests with executable/script content types where uploads exist.",
  fix="Validate real content type, store uploads non-executable, and scan uploads.",
  ver=["automated","dast"],auto="PARTIALLY_AUTOMATED",cwe=["CWE-434"],owasp="A04:2021",
  tests=["UPLOAD-001"],dast=["DAST-UPLOAD-001"]),
R("REQ-127","CSRF security tests","Testing","Medium",
  desc="The audit must execute CSRF tests (state-changing requests without/with foreign tokens).",
  fix="Fix any state-changing endpoint accepting cross-origin forged requests.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-352"],owasp="A01:2021",
  tests=["CSRF-001"],dast=["DAST-CSRF-001"]),
R("REQ-128","IDOR/BOLA security tests","Testing","High",
  desc="The audit must execute IDOR/BOLA tests across sequential/predictable object ids with multiple accounts.",
  fix="Enforce object-level authorization on every detail route.",
  ver=["automated","dast"],auto="FULLY_AUTOMATED",cwe=["CWE-639"],owasp="A01:2021",
  tests=["IDOR-001"],dast=["DAST-IDOR-001"]),
R("REQ-129","SAST findings manually validated","Security Process","Medium",
  desc="Static findings must be triaged: confirmed, false-positive or needs-context before reporting as vulnerabilities.",
  fix="Triage SAST output per finding and record the verdict in the audit trail.",
  ver=["manual"],auto="MANUAL",cwe=[],owasp="A09:2021",manual=True),
R("REQ-130","Findings contain evidence/source location","Security Process","Medium",
  desc="Every finding must carry reproducible evidence (file/line for code, request/response for runtime, target/port for network).",
  fix="Platform guarantee: findings without evidence are rejected by the correlation engine.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A09:2021"),
R("REQ-131","High/critical findings have remediation and retest evidence","Security Process","Medium",
  desc="Every High/Critical finding must include remediation guidance and, after fixing, retest evidence.",
  fix="Platform guarantee: remediation text is mandatory; run a retest to attach after-evidence.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A09:2021"),
R("REQ-132","Generated/vendor artifacts appropriately excluded","Security Process","Low",
  desc="SAST must exclude vendor/generated code (node_modules, .venv, migrations autogen, minified assets) to avoid noise.",
  fix="Platform guarantee: the scanner applies a maintained exclusion list.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A05:2021"),
R("REQ-133","Scanner rules/configuration version-controlled","Security Process","Low",
  desc="Scanner rule sets and audit configuration must be version-controlled and reviewable.",
  fix="Platform guarantee: rules live in requirements/*.yml and rules/*.yml inside the repository.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A05:2021"),
R("REQ-134","Scan targets exact project/version/environment","Testing","Medium",
  desc="Each audit must record exactly which source (repo/branch/commit or path) and environment were scanned.",
  fix="Platform guarantee: audits store source type, commit SHA/path and timestamp.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A05:2021"),
R("REQ-135","Findings mapped to CWE/OWASP","Security Process","Low",
  desc="Every finding must be mapped to CWE identifiers and the OWASP Top 10 category.",
  fix="Platform guarantee: all rules and checks carry CWE/OWASP metadata.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A09:2021"),
R("REQ-136","DAST targets the running Django application","Testing","Medium",
  desc="DAST must run against the actual application instance started for this audit, not an arbitrary target.",
  fix="Platform guarantee: the sandbox records the base URL and ties DAST evidence to it.",
  ver=["internal","dast"],auto="FULLY_AUTOMATED",cwe=[],owasp="A05:2021",
  dast=["DAST-HEALTH-001"]),
R("REQ-137","Final assessment correlates requirements, SAST, DAST and network evidence","Security Process","High",
  desc="The final report must correlate requirement statuses with SAST, DAST, network and dependency evidence, without gaps.",
  fix="Platform guarantee: the correlation engine produces the unified requirement/evidence matrix.",
  ver=["internal"],auto="FULLY_AUTOMATED",cwe=[],owasp="A09:2021"),
]
