"""SAST rule registry.

Every rule carries severity, CWE/OWASP mapping, default confidence and the
requirements it produces evidence for.  Confidence may be upgraded at runtime
by taint analysis (spec 19): e.g. ``mark_safe(trusted_static)`` stays
*Potential* while ``mark_safe(request.GET['name'])`` becomes *Confirmed*.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Rule:
    id: str
    title: str
    severity: str
    confidence: str                       # default; may be upgraded by taint
    category: str
    cwe: tuple
    owasp: str
    message: str
    remediation: str
    requirements: tuple = field(default_factory=tuple)


R = Rule

RULES: dict[str, Rule] = {r.id: r for r in [
    # --- dynamic code / injection -----------------------------------------
    R("DYN-001", "Dynamic code execution (eval/exec/compile)", "Critical", "High",
      "Injection", ("CWE-95",), "A03:2021",
      "eval()/exec()/compile() executes arbitrary Python; with request data this is RCE.",
      "Remove dynamic code execution; use data literals (ast.literal_eval) or dispatch tables.",
      ("REQ-029",)),
    R("DYN-002", "Dynamic import (__import__)", "High", "Medium",
      "Injection", ("CWE-95",), "A03:2021",
      "__import__() with dynamic module names can load attacker-controlled code.",
      "Use static imports; if dynamic loading is required, validate against an allowlist.",
      ("REQ-029",)),
    R("SQLI-001", "Dynamic SQL via cursor.execute", "Critical", "High",
      "Injection", ("CWE-89",), "A03:2021",
      "SQL statement built without placeholders (f-string/%/format or variable).",
      "Use parameterized queries: cursor.execute(sql, params) with %s placeholders.",
      ("REQ-008", "REQ-041")),
    R("SQLI-002", "Dynamic SQL via .raw()/.extra()", "Critical", "High",
      "Injection", ("CWE-89",), "A03:2021",
      "QuerySet.raw()/extra() called with dynamically built SQL.",
      "Parameterize raw SQL or rewrite with ORM querysets.",
      ("REQ-008", "REQ-041")),
    R("SQLI-003", "Dynamic SQL via RawSQL", "Critical", "High",
      "Injection", ("CWE-89",), "A03:2021",
      "RawSQL() constructed from dynamic strings.",
      "Use RawSQL with static SQL and parameters only.",
      ("REQ-008", "REQ-041")),
    R("SQLI-004", "String-built SQL expression", "High", "Medium",
      "Injection", ("CWE-89",), "A03:2021",
      "SQL text assembled with %/format/f-string before execution.",
      "Pass user-controlled values as query parameters, never into the SQL text.",
      ("REQ-008", "REQ-041")),
    R("TPL-001", "Server-side template injection risk", "Critical", "High",
      "Injection", ("CWE-1336",), "A03:2021",
      "Template source constructed from dynamic data (Template(...)/from_string()).",
      "Render fixed templates with user data in the context only.",
      ("REQ-078",)),
    R("XXE-001", "XML parsing without hardened parser", "Medium", "Medium",
      "Injection", ("CWE-611",), "A05:2021",
      "XML parsed with a parser that may resolve external entities.",
      "Use defusedxml for untrusted XML input.",
      ("REQ-079",)),
    R("DOS-001", "Regular expression with nested quantifiers (ReDoS risk)", "Low", "Potential",
      "Availability", ("CWE-1333",), "A03:2021",
      "Regex pattern contains nested quantifiers prone to catastrophic backtracking.",
      "Simplify the pattern, bound input length, and test with long inputs.",
      ("REQ-077",)),

    # --- command injection --------------------------------------------------
    R("CMD-001", "Shell command execution (os.system/os.popen)", "Critical", "High",
      "Injection", ("CWE-78",), "A03:2021",
      "os.system()/os.popen() invokes a shell; any dynamic input enables command injection.",
      "Use subprocess with an argument list and shell=False.",
      ("REQ-031",)),
    R("CMD-002", "subprocess with shell=True", "Critical", "High",
      "Injection", ("CWE-78",), "A03:2021",
      "subprocess executed through the shell; dynamic input enables command injection.",
      "Pass commands as argument lists with shell=False.",
      ("REQ-031",)),
    R("CMD-003", "subprocess with dynamic argument", "High", "Medium",
      "Injection", ("CWE-78",), "A03:2021",
      "subprocess invoked with a runtime-valued argument; validate it even without shell=True.",
      "Validate arguments against an allowlist before execution.",
      ("REQ-031",)),

    # --- deserialization ----------------------------------------------------
    R("DESER-001", "Pickle deserialization", "High", "High",
      "Injection", ("CWE-502",), "A08:2021",
      "pickle.load()/loads() executes arbitrary code on attacker-controlled data.",
      "Use JSON or signed/serialized formats that cannot execute code.",
      ("REQ-030",)),
    R("DESER-002", "Unsafe YAML loading", "High", "High",
      "Injection", ("CWE-502",), "A08:2021",
      "yaml.load() without SafeLoader can instantiate arbitrary Python objects.",
      "Use yaml.safe_load() or pass Loader=yaml.SafeLoader.",
      ("REQ-030", "REQ-080")),
    R("DESER-003", "Marshal/shelve deserialization", "Medium", "Medium",
      "Injection", ("CWE-502",), "A08:2021",
      "marshal/shelve data is not safe for untrusted input.",
      "Avoid marshal/shelve for external data; use JSON.",
      ("REQ-030",)),

    # --- XSS ----------------------------------------------------------------
    R("XSS-001", "mark_safe on dynamic content", "High", "Medium",
      "XSS", ("CWE-79",), "A03:2021",
      "mark_safe() disables autoescaping for its argument.",
      "Only mark trusted/sanitized content safe; prefer format_html().",
      ("REQ-028", "REQ-027")),
    R("XSS-002", "|safe filter in template", "Medium", "Medium",
      "XSS", ("CWE-79",), "A03:2021",
      "The |safe filter disables autoescaping for the rendered value.",
      "Remove |safe unless the value is guaranteed trusted/sanitized.",
      ("REQ-027",)),
    R("XSS-003", "autoescape disabled in template", "Medium", "High",
      "XSS", ("CWE-79",), "A03:2021",
      "autoescape off disables output encoding for the whole block.",
      "Re-enable autoescaping; escape any dynamic value manually if unavoidable.",
      ("REQ-027",)),

    # --- file security --------------------------------------------------------
    R("PATH-001", "Dynamic file path (open)", "Medium", "Medium",
      "File Security", ("CWE-22",), "A01:2021",
      "open() called with a runtime-derived path; traversal risk if user-controlled.",
      "Resolve against a base directory and verify containment before use.",
      ("REQ-032", "REQ-036")),
    R("PATH-002", "Dynamic file serving", "High", "Medium",
      "File Security", ("CWE-73",), "A01:2021",
      "FileResponse/sendfile with a runtime-derived path can expose arbitrary files.",
      "Authorize the object behind the file and confine the path.",
      ("REQ-032", "REQ-036", "REQ-087")),
    R("TMP-001", "Insecure temporary file (mktemp)", "Low", "High",
      "File Security", ("CWE-377",), "A05:2021",
      "tempfile.mktemp creates a predictable name vulnerable to races.",
      "Use tempfile.mkstemp()/NamedTemporaryFile.",
      ("REQ-035",)),
    R("UPLOAD-001", "Upload handling needs validation review", "Low", "Potential",
      "File Security", ("CWE-434",), "A04:2021",
      "request.FILES consumed without visible content-type/size validation.",
      "Validate real content type and size; store uploads outside executable paths.",
      ("REQ-033",)),

    # --- SSRF / redirect ------------------------------------------------------
    R("SSRF-001", "Server-side request with dynamic URL", "High", "Medium",
      "SSRF", ("CWE-918",), "A10:2021",
      "HTTP client called with a runtime-derived URL.",
      "Allowlist schemes/hosts and block private/internal ranges before fetching.",
      ("REQ-037",)),
    R("REDIR-001", "Redirect to dynamic destination", "Medium", "Medium",
      "HTTP/Web", ("CWE-601",), "A01:2021",
      "redirect()/HttpResponseRedirect with a runtime-derived target.",
      "Validate with url_has_allowed_host_and_scheme() or redirect by route name.",
      ("REQ-038", "REQ-081")),

    # --- secrets ---------------------------------------------------------------
    R("SECRET-001", "Hardcoded Django SECRET_KEY", "Critical", "Confirmed",
      "Secrets", ("CWE-798",), "A05:2021",
      "SECRET_KEY assigned from a string literal in source.",
      "Load SECRET_KEY from environment/secret manager and rotate the exposed key.",
      ("REQ-013",)),
    R("SECRET-002", "Hardcoded credential", "High", "Medium",
      "Secrets", ("CWE-798",), "A05:2021",
      "Password/API key/token assigned from a string literal.",
      "Move the value to environment/secret manager and rotate it.",
      ("REQ-013", "REQ-042", "REQ-114")),
    R("SECRET-003", "Private key material present", "Critical", "Confirmed",
      "Secrets", ("CWE-321",), "A02:2021",
      "PEM private key material found in the repository.",
      "Remove the key, purge history, and rotate it immediately.",
      ("REQ-014",)),
    R("SECRET-004", "AWS access key detected", "Critical", "Confirmed",
      "Secrets", ("CWE-798",), "A05:2021",
      "AWS access key id pattern found in source.",
      "Rotate the key in IAM and load credentials from environment/roles.",
      ("REQ-013", "REQ-014")),
    R("SECRET-005", "GitHub token detected", "Critical", "Confirmed",
      "Secrets", ("CWE-798",), "A05:2021",
      "GitHub personal access token pattern found in source.",
      "Revoke and reissue the token; load it from environment.",
      ("REQ-013", "REQ-014")),
    R("SECRET-006", "Stripe secret key detected", "Critical", "Confirmed",
      "Secrets", ("CWE-798",), "A05:2021",
      "Stripe live/secret key pattern found in source.",
      "Roll the key in the Stripe dashboard and load it from environment.",
      ("REQ-013",)),
    R("SECRET-007", "Hardcoded JWT/signing key", "High", "Medium",
      "Secrets", ("CWE-321",), "A02:2021",
      "JWT signing key or crypto key assigned from a literal.",
      "Store signing keys in environment/KMS and rotate.",
      ("REQ-013", "REQ-064")),

    # --- cryptography -----------------------------------------------------------
    R("CRYPTO-001", "Weak hash algorithm (MD5/SHA1)", "Medium", "High",
      "Cryptography", ("CWE-328",), "A02:2021",
      "MD5/SHA1 used; unsuitable for any security purpose.",
      "Use SHA-256+ or HMAC-SHA256; document non-security uses.",
      ("REQ-062",)),
    R("CRYPTO-002", "Insecure randomness for security value", "High", "Medium",
      "Cryptography", ("CWE-330",), "A02:2021",
      "random module used to derive a token/secret/key-like value.",
      "Use the secrets module for security-sensitive randomness.",
      ("REQ-064",)),
    R("CRYPTO-004", "Weak/legacy cipher usage", "High", "Medium",
      "Cryptography", ("CWE-327",), "A02:2021",
      "Legacy cipher or insecure mode (DES/ECB/Blowfish) referenced.",
      "Use AES-GCM or ChaCha20-Poly1305 via a vetted library.",
      ("REQ-063",)),

    # --- auth/DRF ------------------------------------------------------------------
    R("AUTHZ-001", "AllowAny permission on API view", "Medium", "High",
      "Broken Access Control", ("CWE-284",), "A01:2021",
      "AllowAny explicitly opens the view to anonymous callers.",
      "Ensure the endpoint is genuinely public and document the justification.",
      ("REQ-047", "REQ-046")),
    R("AUTHZ-002", "Empty permission_classes", "High", "High",
      "Broken Access Control", ("CWE-862",), "A01:2021",
      "permission_classes=[] disables authorization for the view.",
      "Set explicit permission classes (IsAuthenticated or stricter).",
      ("REQ-046", "REQ-095", "REQ-003", "REQ-002")),
    R("AUTHZ-003", "Empty authentication_classes", "Medium", "Medium",
      "Broken Access Control", ("CWE-306",), "A07:2021",
      "authentication_classes=[] disables authentication for the view.",
      "Configure explicit authentication classes.",
      ("REQ-045", "REQ-001")),
    R("AUTHZ-OBJECT-001", "Detail view without visible object-level authorization",
      "Medium", "Potential",
      "Broken Access Control", ("CWE-639",), "A01:2021",
      "Detail/retrieve view does not override get_queryset or set object permissions.",
      "Scope get_queryset to request.user/tenant and check object permissions.",
      ("REQ-004", "REQ-048", "REQ-096", "REQ-002")),
    R("SER-001", "Request data written without strict serializer validation",
      "High", "Medium",
      "API Security", ("CWE-20",), "A03:2021",
      "request.data flows into model create/update bypassing serializer validation.",
      "Bind input through a serializer and call is_valid(raise_exception=True).",
      ("REQ-051", "REQ-007", "REQ-073")),
    R("MASS-001", "Mass assignment via **request.data", "High", "High",
      "API Security", ("CWE-915",), "A04:2021",
      "**request.data unpacked into a model constructor/update accepts arbitrary fields.",
      "Whitelist fields through serializers; never spread request data into models.",
      ("REQ-073", "REQ-051")),
    R("SENSITIVE-001", "Sensitive field exposed by serializer", "Medium", "Medium",
      "API Security", ("CWE-200",), "A01:2021",
      "Serializer Meta.fields includes password/secret/token-like fields.",
      "Exclude sensitive fields or mark them write_only.",
      ("REQ-044", "REQ-100")),
    R("METHOD-001", "TRACE/unsafe HTTP methods exposed", "Low", "Potential",
      "HTTP/Web", ("CWE-749",), "A05:2021",
      "View configuration exposes TRACE or an excessive method list.",
      "Restrict http_method_names/@api_view to required methods only.",
      ("REQ-050",)),

    # --- misc -----------------------------------------------------------------------
    R("CSRF-001", "CSRF exemption", "Medium", "Medium",
      "CSRF", ("CWE-352",), "A01:2021",
      "@csrf_exempt disables CSRF validation for the view.",
      "Remove the exemption or protect the endpoint another way (token auth, SameSite).",
      ("REQ-009",)),
    R("LOG-001", "Sensitive value possibly logged", "Medium", "Medium",
      "Logging", ("CWE-532",), "A09:2021",
      "Logging call references password/token/secret/key-like values.",
      "Exclude sensitive values from log output.",
      ("REQ-056",)),
    R("LOG-002", "User-controlled value logged (log injection risk)", "Low", "Potential",
      "Logging", ("CWE-117",), "A09:2021",
      "Request-controlled data written to logs without sanitization.",
      "Strip control characters/newlines or log structured fields.",
      ("REQ-057",)),
    R("RACE-001", "Read-modify-write on model field", "Low", "Potential",
      "Business Logic", ("CWE-362",), "A04:2021",
      "Object fetched then field incremented in Python (race-prone).",
      "Use F() expressions / select_for_update() inside a transaction.",
      ("REQ-074",)),
]}


def get(rule_id: str) -> Rule:
    return RULES[rule_id]
